### ISSUE TITLE
Error: Not found: 'dart:js'

### ISSUE THREAD

**Issue by maykhid** [JideGuru/flutter_drawing_board#1]
Trying to run this project but I'm getting this error `Not found: 'dart:js'`

**Error log:**
: Error: Not found: 'dart:js'
lib/…/widgets/canvas_side_bar.dart:2
import 'dart:js' as js;
       ^
: Error: Undefined name 'context'.
lib/…/widgets/canvas_side_bar.dart:308
      js.context.callMethod('open', [url,'_blank']);
         ^^^^^^^
Unhandled exception:
FileSystemException(uri=org-dartlang-untranslatable-uri:dart%3Ajs; message=StandardFileSystem only supports file:* and data:* URIs)
#0      StandardFileSystem.entityForUri (package:front_end/src/api_prototype/standard_file_system.dart:34:7)
#1      asFileUri (package:vm/kernel_front_end.dart:659:37)
#2      writeDepfile (package:vm/kernel_front_end.dart:799:21)
<asynchronous suspension>
#3      FrontendCompiler.compile (package:frontend_server/frontend_server.dart:625:9)
<asynchronous suspension>

#4      starter (package:frontend_server/frontend_server.dart:1451:12)
<asynchronous suspension>
#5      main (file:///opt/s/w/ir/x/w/sdk/pkg/frontend_server/bin/frontend_server_starter.dart:10:14)
<asynchronous suspension>
2

Command PhaseScriptExecution failed with a nonzero exit code

** BUILD FAILED **

Exception: Build process failed
Exited

I'm running this on Flutter 3.3.2 and haven't done anything extra on the project. How to fix?

**Comment by JideGuru** [comment]
@maykhid What platform are you trying to build for?

**Comment by maykhid** [comment]
> @maykhid What platform are you trying to build for?

MacOS

**Comment by JideGuru** [comment]
@maykhid I just pushed a commit now. Do a git pull and try again let's see if it's fixed

**Comment by maykhid** [comment]
> @maykhid I just pushed a commit now. Do a git pull and try again let's see if it's fixed
> 

Works now. 

Can you share what the issue was?

**Comment by JideGuru** [comment]
Dart JS only works for flutter web so I had to replace it with a package that works with other platforms

**Comment by maykhid** [comment]
> Dart JS only works for flutter web so I had to replace it with a package that works with other platforms

Oh okay. Makes sense 👍
