### ISSUE TITLE
Is it possible to get SVG output?

### ISSUE THREAD

**Issue by kiannrezaa** [JideGuru/flutter_drawing_board#14]
I'm trying to implement a collaborative whiteboard. For that to work efficiently, I need to be able to get access to all points and lines drawn on the canvas. Is it possible to do that? Or at least get the SVG output of the canvas?

**Comment by JideGuru** [comment]
Yes, you can get access to all the points. there's a List variable that has all the points in the drawing_canvas.dart file

https://github.com/JideGuru/flutter_drawing_board/blob/01176575c55ce3a284f74df47fd016564ddc0ee3/lib/view/drawing_canvas/drawing_canvas.dart#L20
